"""add_pin_columns_to_reconciliation_results

Revision ID: 14d10aff0cb0
Revises: df869f8ed9f8
Create Date: 2026-07-10 21:23:58.919262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d10aff0cb0'
down_revision: Union[str, Sequence[str], None] = 'df869f8ed9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_reconciliation_results', sa.Column('sap_pin', sa.String(length=100), nullable=True))
    op.add_column('session_reconciliation_results', sa.Column('kra_pin', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_reconciliation_results', 'kra_pin')
    op.drop_column('session_reconciliation_results', 'sap_pin')
    # ### end Alembic commands ###
