"""create_reconciliation_sessions_and_session_invoices

Revision ID: 25ba1a38e195
Revises: ee725638eb0d
Create Date: 2026-07-10 12:18:07.165101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ba1a38e195'
down_revision: Union[str, Sequence[str], None] = 'ee725638eb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('is_compared', sa.Boolean(), nullable=False),
    sa.Column('comparison_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reconciliation_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_sessions'))
    )
    op.create_index(op.f('ix_reconciliation_sessions_user_id'), 'reconciliation_sessions', ['user_id'], unique=False)
    op.create_table('session_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('SAP', 'KRA', name='invoicesource', native_enum=False), nullable=False),
    sa.Column('pin', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('cu_number', sa.String(length=100), nullable=False),
    sa.Column('vat_group', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['reconciliation_sessions.id'], name=op.f('fk_session_invoices_session_id_reconciliation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_invoices'))
    )
    op.create_index('ix_session_invoices_session_cu', 'session_invoices', ['session_id', 'cu_number'], unique=False)
    op.create_index('ix_session_invoices_session_id', 'session_invoices', ['session_id'], unique=False)
    op.create_index('ix_session_invoices_session_source', 'session_invoices', ['session_id', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_invoices_session_source', table_name='session_invoices')
    op.drop_index('ix_session_invoices_session_id', table_name='session_invoices')
    op.drop_index('ix_session_invoices_session_cu', table_name='session_invoices')
    op.drop_table('session_invoices')
    op.drop_index(op.f('ix_reconciliation_sessions_user_id'), table_name='reconciliation_sessions')
    op.drop_table('reconciliation_sessions')
    # ### end Alembic commands ###
