"""Add enterprise settings tables

Revision ID: 27d2cfa7b5ca
Revises: dd58b3443d62
Create Date: 2026-07-13 14:28:26.898526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d2cfa7b5ca'
down_revision: Union[str, Sequence[str], None] = 'dd58b3443d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('company_db', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sap_connections'))
    )
    op.create_index(op.f('ix_sap_connections_id'), 'sap_connections', ['id'], unique=False)
    op.create_table('setting_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setting_audit_logs'))
    )
    op.create_index(op.f('ix_setting_audit_logs_id'), 'setting_audit_logs', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_connection_id', sa.Integer(), nullable=True),
    sa.Column('amount_tolerance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_amount_policy', sa.Enum('SKIP', 'REJECT_SESSION', 'TREAT_AS_ZERO', name='baseamountpolicy', native_enum=False, length=50), nullable=False),
    sa.Column('unmapped_vat_policy', sa.Enum('REJECT_INVOICE', 'NEEDS_REVIEW', name='unmappedvatpolicy', native_enum=False, length=50), nullable=False),
    sa.Column('ignore_missing_cu', sa.Boolean(), nullable=False),
    sa.Column('include_credit_notes', sa.Boolean(), nullable=False),
    sa.Column('include_debit_notes', sa.Boolean(), nullable=False),
    sa.Column('skip_cancelled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_connection_id'], ['sap_connections.id'], name=op.f('fk_system_settings_active_connection_id_sap_connections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('vat_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.Enum('SALES', 'PURCHASES', name='vatmodule', native_enum=False, length=20), nullable=False),
    sa.Column('sap_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('canonical_value', sa.Enum('VAT_16', 'VAT_8', 'ZERO_RATED', 'EXEMPT', name='vatratecategory', native_enum=False, length=50), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_system_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['sap_connections.id'], name=op.f('fk_vat_mappings_connection_id_sap_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vat_mappings')),
    sa.UniqueConstraint('connection_id', 'module', 'sap_code', name='uq_connection_module_sap_code')
    )
    op.create_index(op.f('ix_vat_mappings_id'), 'vat_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vat_mappings_id'), table_name='vat_mappings')
    op.drop_table('vat_mappings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_setting_audit_logs_id'), table_name='setting_audit_logs')
    op.drop_table('setting_audit_logs')
    op.drop_index(op.f('ix_sap_connections_id'), table_name='sap_connections')
    op.drop_table('sap_connections')
    # ### end Alembic commands ###
