"""add_kra_section_mappings

Revision ID: 442da9e37d7f
Revises: 27d2cfa7b5ca
Create Date: 2026-07-14 21:26:54.604209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442da9e37d7f'
down_revision: Union[str, Sequence[str], None] = '27d2cfa7b5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('kra_section_mappings', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'kra_section_mappings')
    # ### end Alembic commands ###
