"""refactor_kra_parsing_profiles

Revision ID: 6f7b662a0fc3
Revises: fa26cca76a6e
Create Date: 2026-07-16 02:51:33.316561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7b662a0fc3'
down_revision: Union[str, Sequence[str], None] = 'fa26cca76a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kra_vat_mappings', sa.Column('description', sa.String(length=200), nullable=False))
    op.add_column('system_settings', sa.Column('kra_parsing_profiles', sa.JSON(), nullable=True, comment='JSON configuration mapping KRA section prefixes to CSV parsing rules'))
    op.drop_column('system_settings', 'kra_csv_invoice_number_column')
    op.drop_column('system_settings', 'kra_csv_invoice_date_column')
    op.drop_column('system_settings', 'kra_csv_base_amount_column')
    op.drop_column('system_settings', 'kra_csv_cu_number_column')
    op.drop_column('system_settings', 'kra_csv_pin_column')
    op.drop_column('system_settings', 'kra_csv_partner_name_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('kra_csv_partner_name_column', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('system_settings', sa.Column('kra_csv_pin_column', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('system_settings', sa.Column('kra_csv_cu_number_column', sa.INTEGER(), server_default=sa.text('4'), autoincrement=False, nullable=False))
    op.add_column('system_settings', sa.Column('kra_csv_base_amount_column', sa.INTEGER(), server_default=sa.text('6'), autoincrement=False, nullable=False))
    op.add_column('system_settings', sa.Column('kra_csv_invoice_date_column', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.add_column('system_settings', sa.Column('kra_csv_invoice_number_column', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=False))
    op.drop_column('system_settings', 'kra_parsing_profiles')
    op.drop_column('kra_vat_mappings', 'description')
    # ### end Alembic commands ###
