"""add_sap_field_mappings

Revision ID: a15d71db5db4
Revises: 442da9e37d7f
Create Date: 2026-07-15 16:14:34.322037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15d71db5db4'
down_revision: Union[str, Sequence[str], None] = '442da9e37d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_field_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.Enum('SALES', 'PURCHASES', name='vatmodule', native_enum=False, length=20), nullable=False),
    sa.Column('internal_field', sa.Enum('INVOICE_NUMBER', 'PARTNER_NAME', 'INVOICE_DATE', 'PIN', 'CU_NUMBER', 'CU_SERIAL', 'BASE_AMOUNT', 'VAT_GROUP', name='internalfield', native_enum=False, length=50), nullable=False),
    sa.Column('source_type', sa.Enum('HEADER', 'LINE', name='sourcetype', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sap_field', sa.String(length=100), nullable=False),
    sa.Column('transformation', sa.Enum('NONE', 'BEFORE_SLASH', 'AFTER_SLASH', 'REGEX', 'REGEX_REPLACE', 'TRIM', 'UPPERCASE', 'LOWERCASE', name='transformationtype', native_enum=False, length=50), nullable=False),
    sa.Column('transformation_value', sa.String(length=255), nullable=True),
    sa.Column('validation_regex', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sap_field_mappings')),
    sa.UniqueConstraint('module', 'internal_field', 'priority', name='uq_sap_mapping_module_field_priority')
    )
    op.create_index(op.f('ix_sap_field_mappings_id'), 'sap_field_mappings', ['id'], unique=False)
    op.add_column('session_invoices', sa.Column('cu_serial', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_invoices', 'cu_serial')
    op.drop_index(op.f('ix_sap_field_mappings_id'), table_name='sap_field_mappings')
    op.drop_table('sap_field_mappings')
    # ### end Alembic commands ###
