"""per_company_sap_settings

Revision ID: c2e0605bf454
Revises: e83e03efb56f
Create Date: 2026-07-16 20:56:56.214255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import json

# revision identifiers, used by Alembic.
revision: str = 'c2e0605bf454'
down_revision: Union[str, Sequence[str], None] = 'e83e03efb56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to per-company SAP connections and settings."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_sap_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('company_db', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_sap_connections_company_id_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_sap_connections'))
    )
    op.create_index(op.f('ix_company_sap_connections_company_id'), 'company_sap_connections', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_sap_connections_id'), 'company_sap_connections', ['id'], unique=False)
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('active_connection_id', sa.Integer(), nullable=True),
    sa.Column('amount_tolerance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_amount_policy', sa.Enum('SKIP', 'REJECT_SESSION', 'TREAT_AS_ZERO', name='baseamountpolicy', native_enum=False, length=50), nullable=False),
    sa.Column('unmapped_vat_policy', sa.Enum('REJECT_INVOICE', 'NEEDS_REVIEW', name='unmappedvatpolicy', native_enum=False, length=50), nullable=False),
    sa.Column('ignore_missing_cu', sa.Boolean(), nullable=False),
    sa.Column('include_credit_notes', sa.Boolean(), nullable=False),
    sa.Column('include_debit_notes', sa.Boolean(), nullable=False),
    sa.Column('skip_cancelled', sa.Boolean(), nullable=False),
    sa.Column('purchase_cu_source', sa.String(length=50), nullable=False, comment='SAP field holding the CU number on Purchase Invoices (e.g. U_CUINV, NumAtCard, Comments, JournalMemo, Reference1)'),
    sa.Column('kra_parsing_profiles', sa.JSON(), nullable=True, comment='JSON configuration mapping KRA section prefixes to CSV parsing rules'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_connection_id'], ['company_sap_connections.id'], name=op.f('fk_company_settings_active_connection_id_company_sap_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_settings_company_id_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_settings'))
    )
    op.create_index(op.f('ix_company_settings_company_id'), 'company_settings', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_settings_id'), 'company_settings', ['id'], unique=False)

    # ---- Data migration: move global settings into the first company ----
    bind = op.get_bind()
    # Resolve (or create) a default company to host the legacy global config.
    company_id = bind.execute(sa.text("SELECT id FROM company ORDER BY id LIMIT 1")).scalar()
    if company_id is None:
        bind.execute(
            sa.text(
                "INSERT INTO company (name, kra_pin, timezone, currency, fiscal_year_start_month, created_at, updated_at) "
                "VALUES ('Default Company', NULL, 'Africa/Nairobi', 'KES', 1, now(), now())"
            )
        )
        company_id = bind.execute(sa.text("SELECT currval('company_id_seq')")).scalar()

    legacy_conn_id = bind.execute(sa.text("SELECT id FROM sap_connections ORDER BY id LIMIT 1")).scalar()
    new_conn_id = None
    if legacy_conn_id is not None:
        row = bind.execute(
            sa.text(
                "SELECT name, base_url, company_db, username, password, verify_ssl, is_active, version, created_at, updated_at, updated_by_id "
                "FROM sap_connections WHERE id = :cid"
            ),
            {"cid": legacy_conn_id},
        ).first()
        if row is not None:
            bind.execute(
                sa.text(
                    "INSERT INTO company_sap_connections "
                    "(company_id, name, base_url, company_db, username, password, verify_ssl, is_active, version, created_at, updated_at, updated_by_id) "
                    "VALUES (:company_id, :name, :base_url, :company_db, :username, :password, :verify_ssl, :is_active, :version, :created_at, :updated_at, :updated_by_id)"
                ),
                {
                    "company_id": company_id,
                    "name": row[0],
                    "base_url": row[1],
                    "company_db": row[2],
                    "username": row[3],
                    "password": row[4],
                    "verify_ssl": row[5],
                    "is_active": row[6],
                    "version": row[7],
                    "created_at": row[8],
                    "updated_at": row[9],
                    "updated_by_id": row[10],
                },
            )
            new_conn_id = bind.execute(sa.text("SELECT currval('company_sap_connections_id_seq')")).scalar()

    legacy_setting = bind.execute(sa.text("SELECT id FROM system_settings ORDER BY id LIMIT 1")).scalar()
    if legacy_setting is not None:
        srow = bind.execute(
            sa.text(
                "SELECT amount_tolerance, base_amount_policy, unmapped_vat_policy, ignore_missing_cu, "
                "include_credit_notes, include_debit_notes, skip_cancelled, purchase_cu_source, "
                "kra_parsing_profiles, version, updated_at, updated_by_id "
                "FROM system_settings WHERE id = :sid"
            ),
            {"sid": legacy_setting},
        ).first()
        bind.execute(
            sa.text(
                "INSERT INTO company_settings "
                "(company_id, active_connection_id, amount_tolerance, base_amount_policy, unmapped_vat_policy, "
                "ignore_missing_cu, include_credit_notes, include_debit_notes, skip_cancelled, "
                "purchase_cu_source, kra_parsing_profiles, version, updated_at, updated_by_id) "
                "VALUES (:company_id, :active_connection_id, :amount_tolerance, :base_amount_policy, :unmapped_vat_policy, "
                ":ignore_missing_cu, :include_credit_notes, :include_debit_notes, :skip_cancelled, "
                ":purchase_cu_source, :kra_parsing_profiles, :version, :updated_at, :updated_by_id)"
            ),
            {
                "company_id": company_id,
                "active_connection_id": new_conn_id,
                "amount_tolerance": srow[0],
                "base_amount_policy": srow[1],
                "unmapped_vat_policy": srow[2],
                "ignore_missing_cu": srow[3],
                "include_credit_notes": srow[4],
                "include_debit_notes": srow[5],
                "skip_cancelled": srow[6],
                "purchase_cu_source": srow[7],
                "kra_parsing_profiles": json.dumps(srow[8]) if srow[8] is not None else None,
                "version": srow[9],
                "updated_at": srow[10],
                "updated_by_id": srow[11],
            },
        )
        # Migrate VAT mappings from the legacy connection to the new per-company one.
        if new_conn_id is not None:
            bind.execute(
                sa.text(
                    "UPDATE vat_mappings SET connection_id = :new_conn WHERE connection_id = :old_conn"
                ),
                {"new_conn": new_conn_id, "old_conn": legacy_conn_id},
            )
        # Assign the default company to any users that have none.
        bind.execute(
            sa.text("UPDATE users SET company_id = :cid WHERE company_id IS NULL"),
            {"cid": company_id},
        )

    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # Drop the legacy vat_mappings FK before removing sap_connections.
    op.drop_constraint(op.f('fk_vat_mappings_connection_id_sap_connections'), 'vat_mappings', type_='foreignkey')
    op.drop_index(op.f('ix_sap_connections_id'), table_name='sap_connections')
    op.drop_table('sap_connections')
    op.add_column('reconciliation_sessions', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reconciliation_sessions_company_id'), 'reconciliation_sessions', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_reconciliation_sessions_company_id_company'), 'reconciliation_sessions', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    # Backfill existing sessions with the default company before enforcing NOT NULL.
    op.execute(sa.text("UPDATE reconciliation_sessions SET company_id = :cid WHERE company_id IS NULL").bindparams(cid=company_id))
    op.alter_column('reconciliation_sessions', 'company_id', existing_type=sa.Integer(), nullable=False)
    op.add_column('setting_audit_logs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_setting_audit_logs_company_id'), 'setting_audit_logs', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_setting_audit_logs_company_id_company'), 'setting_audit_logs', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_vat_mappings_connection_id_company_sap_connections'), 'vat_mappings', 'company_sap_connections', ['connection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_vat_mappings_connection_id_company_sap_connections'), 'vat_mappings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vat_mappings_connection_id_sap_connections'), 'vat_mappings', 'sap_connections', ['connection_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_setting_audit_logs_company_id_company'), 'setting_audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_setting_audit_logs_company_id'), table_name='setting_audit_logs')
    op.drop_column('setting_audit_logs', 'company_id')
    op.drop_constraint(op.f('fk_reconciliation_sessions_company_id_company'), 'reconciliation_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_reconciliation_sessions_company_id'), table_name='reconciliation_sessions')
    op.drop_column('reconciliation_sessions', 'company_id')
    op.create_table('sap_connections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('company_db', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('verify_ssl', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sap_connections'))
    )
    op.create_index(op.f('ix_sap_connections_id'), 'sap_connections', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('active_connection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_tolerance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('base_amount_policy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unmapped_vat_policy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ignore_missing_cu', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('include_credit_notes', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('include_debit_notes', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('skip_cancelled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_cu_source', sa.VARCHAR(length=50), server_default=sa.text("'U_CUINV'::character varying"), autoincrement=False, nullable=False, comment='SAP field holding the CU number on Purchase Invoices (e.g. U_CUINV, NumAtCard, Comments, JournalMemo, Reference1)'),
    sa.Column('kra_parsing_profiles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON configuration mapping KRA section prefixes to CSV parsing rules'),
    sa.ForeignKeyConstraint(['active_connection_id'], ['sap_connections.id'], name=op.f('fk_system_settings_active_connection_id_sap_connections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.drop_index(op.f('ix_company_settings_id'), table_name='company_settings')
    op.drop_index(op.f('ix_company_settings_company_id'), table_name='company_settings')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_company_sap_connections_id'), table_name='company_sap_connections')
    op.drop_index(op.f('ix_company_sap_connections_company_id'), table_name='company_sap_connections')
    op.drop_table('company_sap_connections')
    # ### end Alembic commands ###
