"""Add pin_matches and partner_name_matches to results

Revision ID: dd58b3443d62
Revises: 14d10aff0cb0
Create Date: 2026-07-12 22:54:40.662905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd58b3443d62'
down_revision: Union[str, Sequence[str], None] = '14d10aff0cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_reconciliation_results', sa.Column('partner_name_matches', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('session_reconciliation_results', sa.Column('pin_matches', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.alter_column('session_reconciliation_results', 'status',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('MATCH', 'MISSING_IN_SAP', 'MISSING_IN_KRA', 'AMOUNT_MISMATCH', 'VAT_MISMATCH', 'MULTIPLE_MISMATCHES', 'DUPLICATE_SOURCE_KEY', name='reconciliationstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_reconciliation_results', 'status',
               existing_type=sa.Enum('MATCH', 'MISSING_IN_SAP', 'MISSING_IN_KRA', 'AMOUNT_MISMATCH', 'VAT_MISMATCH', 'MULTIPLE_MISMATCHES', 'DUPLICATE_SOURCE_KEY', name='reconciliationstatus', native_enum=False),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)
    op.drop_column('session_reconciliation_results', 'pin_matches')
    op.drop_column('session_reconciliation_results', 'partner_name_matches')
    # ### end Alembic commands ###
