"""add_company_and_user_profile_fields

Revision ID: e83e03efb56f
Revises: 52b4ee763eea
Create Date: 2026-07-16 19:06:52.007092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83e03efb56f'
down_revision: Union[str, Sequence[str], None] = '52b4ee763eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kra_pin', sa.String(length=50), nullable=True, comment='Company KRA PIN (e.g. P051234567Q)'),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False, comment='Month (1-12) when the company fiscal year starts'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company'))
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(op.f('fk_users_company_id_company'), 'company', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint(op.f('fk_users_company_id_company'), type_='foreignkey')
        batch_op.drop_column('company_id')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('full_name')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
