/"""Add KRA CSV and VAT mappings

Revision ID: fa26cca76a6e
Revises: f0b1c2d3e4a5
Create Date: 2026-07-16 01:15:45.378188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa26cca76a6e'
down_revision: Union[str, Sequence[str], None] = 'f0b1c2d3e4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kra_vat_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_prefix', sa.String(length=50), nullable=False, comment='E.g., SEC_B'),
    sa.Column('canonical_value', sa.Enum('VAT_16', 'VAT_8', 'ZERO_RATED', 'EXEMPT', name='vatratecategory', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kra_vat_mappings'))
    )
    op.create_index(op.f('ix_kra_vat_mappings_id'), 'kra_vat_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_kra_vat_mappings_section_prefix'), 'kra_vat_mappings', ['section_prefix'], unique=True)
    op.add_column('system_settings', sa.Column('kra_csv_pin_column', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('system_settings', sa.Column('kra_csv_partner_name_column', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.add_column('system_settings', sa.Column('kra_csv_invoice_number_column', sa.Integer(), nullable=False, server_default=sa.text('2')))
    op.add_column('system_settings', sa.Column('kra_csv_invoice_date_column', sa.Integer(), nullable=False, server_default=sa.text('3')))
    op.add_column('system_settings', sa.Column('kra_csv_cu_number_column', sa.Integer(), nullable=False, server_default=sa.text('4')))
    op.add_column('system_settings', sa.Column('kra_csv_vat_group_column', sa.Integer(), nullable=False, server_default=sa.text('5')))
    op.add_column('system_settings', sa.Column('kra_csv_base_amount_column', sa.Integer(), nullable=False, server_default=sa.text('6')))
    op.alter_column('system_settings', 'purchase_cu_source',
               existing_type=sa.VARCHAR(length=50),
               comment='SAP field holding the CU number on Purchase Invoices (e.g. U_CUINV, NumAtCard, Comments, JournalMemo, Reference1)',
               existing_comment='SAP field holding the CU number on Purchase Invoices',
               existing_nullable=False,
               existing_server_default=sa.text("'U_CUINV'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'purchase_cu_source',
               existing_type=sa.VARCHAR(length=50),
               comment='SAP field holding the CU number on Purchase Invoices',
               existing_comment='SAP field holding the CU number on Purchase Invoices (e.g. U_CUINV, NumAtCard, Comments, JournalMemo, Reference1)',
               existing_nullable=False,
               existing_server_default=sa.text("'U_CUINV'::character varying"))
    op.drop_column('system_settings', 'kra_csv_base_amount_column')
    op.drop_column('system_settings', 'kra_csv_vat_group_column')
    op.drop_column('system_settings', 'kra_csv_cu_number_column')
    op.drop_column('system_settings', 'kra_csv_invoice_date_column')
    op.drop_column('system_settings', 'kra_csv_invoice_number_column')
    op.drop_column('system_settings', 'kra_csv_partner_name_column')
    op.drop_column('system_settings', 'kra_csv_pin_column')
    op.drop_index(op.f('ix_kra_vat_mappings_section_prefix'), table_name='kra_vat_mappings')
    op.drop_index(op.f('ix_kra_vat_mappings_id'), table_name='kra_vat_mappings')
    op.drop_table('kra_vat_mappings')
    # ### end Alembic commands ###
