from app.reporting.context import ExportContext
from app.models.reconciliation_session import ReconciliationSession


def build_empty_export_readme(
    session: ReconciliationSession,
    context: ExportContext,
) -> str:
    """Returns the full README.txt content for an empty export archive."""
    return "\n".join([
        "KRA Reconciliation Export",
        "=========================",
        f"Session ID:          {session.id}",
        f"Generated At:        {context.generated_at.isoformat()}",
        f"Generated By:        {context.generated_by}",
        f"Company:             {getattr(session, 'company_db', 'N/A')}",
        f"Session Type:        {session.session_type.value.title()}",
        f"Date Range:          {session.from_date} to {session.to_date}",
        f"Compared:            {'Yes' if session.is_compared else 'No'}",
        "Result:              No reconciliation rows found for this date range.",
    ])
