from openpyxl import Workbook
from openpyxl.styles import Alignment
from openpyxl.utils import get_column_letter

from app.reporting.context import ExportContext
from app.reporting.export_row import ReconciliationExportRow
from app.reporting.styles import (
    AMOUNT_FORMAT, HEADER_FILL, HEADER_FONT, SUBTITLE_FONT,
    TITLE_FONT, VALUE_FONT, WARNING_FILL,
)
from app.reporting.workbook_artifact import WorkbookArtifact
from app.schemas.reconciliation import ReconciliationSummary

from app.models.reconciliation_session import ReconciliationSession
from app.reporting.sheet_definitions import SHEET_DEFINITIONS, SheetDefinition, SheetColumn


def build_all(
    rows: list[ReconciliationExportRow],
    summary: ReconciliationSummary,
    context: ExportContext,
    session: ReconciliationSession,
) -> list[WorkbookArtifact]:
    """Build all workbook artifacts: summary + per-status detail sheets."""
    artifacts: list[WorkbookArtifact] = []

    # 1. Summary workbook
    artifacts.append(_build_summary_workbook(rows, summary, context, session))

    # 2. Detail workbooks
    for sheet_def in SHEET_DEFINITIONS:
        matching_rows = [r for r in rows if sheet_def.statuses and r.status in sheet_def.statuses]
        if not matching_rows and sheet_def.statuses:
            continue
        artifacts.append(_build_detail_workbook(matching_rows, sheet_def, context))

    return artifacts


def _build_summary_workbook(
    rows: list[ReconciliationExportRow],
    summary: ReconciliationSummary,
    context: ExportContext,
    session: ReconciliationSession,
) -> WorkbookArtifact:
    wb = Workbook()
    ws = wb.active
    ws.title = "Summary"

    # Title
    ws.merge_cells("A1:D1")
    ws["A1"] = "Reconciliation Summary"
    ws["A1"].font = TITLE_FONT
    ws.row_dimensions[1].height = 28

    # Metadata section
    metadata = [
        ("Schema Version", context.export_version),
        ("Status Priority Version", "1"),
        ("Generated At", context.generated_at.strftime("%Y-%m-%dT%H:%M:%S.%fZ")),
        ("Generated By", context.generated_by),
        ("App Version", context.app_version),
        ("Session ID", session.id),
        ("Session Type", session.session_type.value.title()),
        ("Date Range", f"{session.from_date} to {session.to_date}"),
        ("Compared", "Yes" if session.is_compared else "No"),
    ]

    row = 3
    for label, value in metadata:
        ws.cell(row=row, column=1, value=label).font = SUBTITLE_FONT
        ws.cell(row=row, column=2, value=value).font = VALUE_FONT
        row += 1

    # Counts section
    row += 1
    ws.cell(row=row, column=1, value="Reconciliation Counts").font = TITLE_FONT
    ws.merge_cells(f"A{row}:D{row}")
    row += 1

    counts = [
        ("Total SAP Invoices", summary.total_sap),
        ("Total KRA Invoices", summary.total_kra),
        ("Matches", summary.matches),
        ("Missing in SAP", summary.missing_in_sap),
        ("Missing in KRA", summary.missing_in_kra),
        ("Mismatches (Total)", summary.mismatches),
        ("  Amount Mismatches", summary.mismatch_stats.amount),
        ("  VAT Mismatches", summary.mismatch_stats.vat),
        ("  Date Mismatches", summary.mismatch_stats.date),
        ("Duplicate CU", summary.duplicate_cu),
        ("Total Rows", len(rows)),
        ("Match Percentage", f"{summary.match_percentage:.1f}%"),
        ("Completion Percentage", f"{summary.completion_percentage:.1f}%"),
    ]

    for label, value in counts:
        ws.cell(row=row, column=1, value=label).font = SUBTITLE_FONT
        ws.cell(row=row, column=2, value=value).font = VALUE_FONT
        row += 1

    # Status priority reference
    row += 2
    ws.cell(row=row, column=1, value="Status Priority Order").font = TITLE_FONT
    ws.merge_cells(f"A{row}:D{row}")
    row += 1

    from app.domain.reconciliation_constants import STATUS_ORDER, STATUS_PRIORITY
    for status in STATUS_ORDER:
        ws.cell(row=row, column=1, value=STATUS_PRIORITY[status]).font = VALUE_FONT
        ws.cell(row=row, column=2, value=status.value).font = VALUE_FONT
        row += 1

    # Column widths
    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 35

    import io
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)

    return WorkbookArtifact(
        zip_path="Summary/01 Summary.xlsx",
        filename="01 Summary.xlsx",
        content=buf.read(),
    )


def _build_detail_workbook(
    rows: list[ReconciliationExportRow],
    sheet_def: SheetDefinition,
    context: ExportContext,
) -> WorkbookArtifact:
    wb = Workbook()
    ws = wb.active
    ws.title = sheet_def.title

    # Header row
    headers = [col.header for col in sheet_def.columns]
    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    ws.row_dimensions[1].height = 32

    # Data rows
    for row_idx, row_data in enumerate(rows, 2):
        for col_idx, col_def in enumerate(sheet_def.columns, 1):
            value = getattr(row_data, col_def.attr)
            cell = ws.cell(row=row_idx, column=col_idx)

            if value is None:
                cell.value = ""
            elif col_def.is_amount:
                cell.value = float(value)
                cell.number_format = AMOUNT_FORMAT
                cell.alignment = Alignment(horizontal="right")
            elif col_def.is_date:
                cell.value = value.isoformat() if hasattr(value, "isoformat") else str(value)
                cell.alignment = Alignment(horizontal="center")
            elif col_def.is_bool:
                cell.value = "Yes" if value else "No"
                cell.alignment = Alignment(horizontal="center")
                if not value:
                    cell.fill = WARNING_FILL
            elif col_def.is_cu:
                cell.value = str(value)
                cell.number_format = "@"  # text format
            else:
                cell.value = str(value)

            cell.font = VALUE_FONT

    # Apply column widths
    for col_idx, col_def in enumerate(sheet_def.columns, 1):
        letter = get_column_letter(col_idx)
        ws.column_dimensions[letter].width = col_def.width

    # Freeze header
    ws.freeze_panes = "A2"

    # Auto-filter
    if rows:
        last_col = get_column_letter(len(headers))
        ws.auto_filter.ref = f"A1:{last_col}{len(rows) + 1}"

    # Add as Excel Table
    if rows:
        last_col = get_column_letter(len(headers))
        table_ref = f"A1:{last_col}{len(rows) + 1}"
        from openpyxl.worksheet.table import Table, TableStyleInfo
        # Sanitize table name for Excel
        safe_name = f"tbl_{sheet_def.title.replace(' ', '_').lower()}"
        table = Table(displayName=safe_name, ref=table_ref)
        table.tableStyleInfo = TableStyleInfo(
            name="TableStyleMedium2",
            showFirstColumn=False,
            showLastColumn=False,
            showRowStripes=True,
            showColumnStripes=False,
        )
        ws.add_table(table)

    import io
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)

    zip_path_prefix = "Details"
    return WorkbookArtifact(
        zip_path=f"{zip_path_prefix}/{sheet_def.filename}",
        filename=sheet_def.filename,
        content=buf.read(),
    )
