LEGAL_SUFFIXES = {
    "LIMITED", "LTD", "COMPANY", "CO", "PLC", "INC", "LLC", "CORP", "CORPORATION", "PVT", "PRIVATE"
}

GEOGRAPHIC_SUFFIXES = {
    "KENYA", "K", "KE"
}

STOP_WORDS = {
    "AND", "OF", "THE", "FOR", "IN"
}

ALLOWED_EXPANSIONS = {
    "KENYA", "KE", "K", "EAST", "AFRICA", "GROUP", "HOLDINGS", "INTERNATIONAL", 
    "SERVICES", "TRADING", "LOGISTICS", "ASSOCIATES", "PARTNERS", "DEVELOPMENT", 
    "SOLUTIONS", "INDUSTRIES", "GLOBAL", "WORLDWIDE", "ENTERPRISES", "SYSTEMS", 
    "TECHNOLOGY", "TECHNOLOGIES"
}
